// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Daniel15.Web.Controllers
{
    public partial class SiteController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SiteController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SiteController Actions { get { return MVC.Site; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Site";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Site";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Projects = "Projects";
            public readonly string Search = "Search";
            public readonly string SocialFeed = "SocialFeed";
            public readonly string TumblrPosts = "TumblrPosts";
            public readonly string FileNotFound = "FileNotFound";
            public readonly string Error = "Error";
            public readonly string Alive = "Alive";
            public readonly string ChatStatus = "ChatStatus";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Projects = "Projects";
            public const string Search = "Search";
            public const string SocialFeed = "SocialFeed";
            public const string TumblrPosts = "TumblrPosts";
            public const string FileNotFound = "FileNotFound";
            public const string Error = "Error";
            public const string Alive = "Alive";
            public const string ChatStatus = "ChatStatus";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _LatestPosts = "_LatestPosts";
                public readonly string _ProjectList = "_ProjectList";
                public readonly string _TumblrPosts = "_TumblrPosts";
                public readonly string FileNotFound = "FileNotFound";
                public readonly string Index = "Index";
                public readonly string Projects = "Projects";
                public readonly string Search = "Search";
                public readonly string SocialFeed = "SocialFeed";
            }
            public readonly string _LatestPosts = "~/Views/Site/_LatestPosts.cshtml";
            public readonly string _ProjectList = "~/Views/Site/_ProjectList.cshtml";
            public readonly string _TumblrPosts = "~/Views/Site/_TumblrPosts.cshtml";
            public readonly string FileNotFound = "~/Views/Site/FileNotFound.cshtml";
            public readonly string Index = "~/Views/Site/Index.cshtml";
            public readonly string Projects = "~/Views/Site/Projects.cshtml";
            public readonly string Search = "~/Views/Site/Search.cshtml";
            public readonly string SocialFeed = "~/Views/Site/SocialFeed.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SiteController : Daniel15.Web.Controllers.SiteController
    {
        public T4MVC_SiteController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ProjectsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Projects()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Projects);
            ProjectsOverride(callInfo);
            return callInfo;
        }

        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Search()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            SearchOverride(callInfo);
            return callInfo;
        }

        partial void SocialFeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult SocialFeed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SocialFeed);
            SocialFeedOverride(callInfo);
            return callInfo;
        }

        partial void TumblrPostsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult TumblrPosts()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TumblrPosts);
            TumblrPostsOverride(callInfo);
            return callInfo;
        }

        partial void FileNotFoundOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult FileNotFound()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FileNotFound);
            FileNotFoundOverride(callInfo);
            return callInfo;
        }

        partial void ErrorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Error()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Error);
            ErrorOverride(callInfo);
            return callInfo;
        }

        partial void AliveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Alive()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Alive);
            AliveOverride(callInfo);
            return callInfo;
        }

        partial void ChatStatusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ChatStatus()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChatStatus);
            ChatStatusOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
